import Provider from "@/providers/SessionProvider";
import "./globals.css";
import type { Metadata } from "next";
import { SimpleFooter } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-200">
        <Provider>
          {children}
          {/* <SimpleFooter /> */}
        </Provider>
      </body>
    </html>
  );
}
